version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    depends_on:
      - redis
    ports:
      - '8081:8081'

volumes:
  redis-data:
    driver: local